// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1dQp_vmFeonmOyhvKAPyiAS9jFCmnIAY',
    appId: '1:558454130320:web:077cc337a3c14634573a15',
    messagingSenderId: '558454130320',
    projectId: 'task-f6eb2',
    authDomain: 'task-f6eb2.firebaseapp.com',
    storageBucket: 'task-f6eb2.firebasestorage.app',
    measurementId: 'G-W4Y6C4KVZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG9ffB95FVZCWPrE9NuWQBVOPmnLA0Pg0',
    appId: '1:558454130320:android:c644217843edf5e1573a15',
    messagingSenderId: '558454130320',
    projectId: 'task-f6eb2',
    storageBucket: 'task-f6eb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrRfbnZUnImBFlFgojE-Z_IjRkF1HZB0U',
    appId: '1:558454130320:ios:720eb178fdd27ca4573a15',
    messagingSenderId: '558454130320',
    projectId: 'task-f6eb2',
    storageBucket: 'task-f6eb2.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrRfbnZUnImBFlFgojE-Z_IjRkF1HZB0U',
    appId: '1:558454130320:ios:720eb178fdd27ca4573a15',
    messagingSenderId: '558454130320',
    projectId: 'task-f6eb2',
    storageBucket: 'task-f6eb2.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1dQp_vmFeonmOyhvKAPyiAS9jFCmnIAY',
    appId: '1:558454130320:web:1f24e55610573ea5573a15',
    messagingSenderId: '558454130320',
    projectId: 'task-f6eb2',
    authDomain: 'task-f6eb2.firebaseapp.com',
    storageBucket: 'task-f6eb2.firebasestorage.app',
    measurementId: 'G-1TG70T76C2',
  );
}
